server:
  port: 8080
#数据库配置
spring:
  datasource:
    username: root
    password: 123456
    #url中database为对应的数据库名称
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  #    配置Redis，Mybatis，开启Mybatis二级缓存等：
  redis:
    # redis数据库索引（默认为0），我们使用索引为3的数据库，避免和其他数据库冲突
    database: 3
    #server host
    # redis服务器地址（默认为localhost）
    host: localhost
    # redis端口（默认为6379）
    port: 6379
    # redis访问密码（默认为空）
    password:
    # redis连接超时时间（单位为毫秒）
    timeout: 5000
    # redis连接池配置
    pool:
      # 最大可用连接数（默认为8，负数表示无限）
      max-active: 8
      # 最大空闲连接数（默认为8，负数表示无限）
      max-idle: 8
      # 最小空闲连接数（默认为0，该值只有为正数才有作用）
      min-idle: 0
      # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
      max-wait: -1
mybatis:
  # Mapper.xml所在的位置
  mapper-locations: classpath:mapper/*.xml
  # 扫描的实体类
  type-aliases-package: com.hhu.springbootframe.entity
  # 开启MyBatis的二级缓存
  configuration:
    cache-enabled: true
#showSql
logging:
  level:
    com.hhu.springbootframe.mapper: debug

